description 'Enables use of /tweet for in character chat.'
server_script 'server.lua'
------------------------------------------------------------------------- Creat by: xPlay City
XXXXXXXXXXXXXXXXXXXX                   XXXXXXXXXXXXXXXXXXXX
 XXXXXXXXXXXXXXXXXXXX                 XXXXXXXXXXXXXXXXXXXX
  XXXXXXXXXXXXXXXXXXXX               XXXXXXXXXXXXXXXXXXXX
   XXXXXXXXXXXXXXXXXXXX             XXXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXXXXX           XXXXXXXXXXXXXXXXXXXX
     XXXXXXXXXXXXXXXXXXXX         XXXXXXXXXXXXXXXXXXXX
      XXXXXXXXXXXXXXXXXXXX       XXXXXXXXXXXXXXXXXXXX
       XXXXXXXXXXXXXXXXXXXX     XXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXX   XXXXXXXXXXXXXXXXXXXX
         XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
          XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
         XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXX   XXXXXXXXXXXXXXXXXXXX
       XXXXXXXXXXXXXXXXXXXX     XXXXXXXXXXXXXXXXXXXX
      XXXXXXXXXXXXXXXXXXXX       XXXXXXXXXXXXXXXXXXXX
     XXXXXXXXXXXXXXXXXXXX         XXXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXXXXX           XXXXXXXXXXXXXXXXXXXX
   XXXXXXXXXXXXXXXXXXXX             XXXXXXXXXXXXXXXXXXXX
  XXXXXXXXXXXXXXXXXXXX               XXXXXXXXXXXXXXXXXXXX
 XXXXXXXXXXXXXXXXXXXX                 XXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXX                   XXXXXXXXXXXXXXXXXXXX















PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP
PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP
PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP
PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP
PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP
PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP
PPPPPPPPPPPPPPPPPPPP                           PPPPPPPPPPPPPPPPPPPP            
PPPPPPPPPPPPPPPPPPPP                            PPPPPPPPPPPPPPPPPPPP         
PPPPPPPPPPPPPPPPPPPP                             PPPPPPPPPPPPPPPPPPPP         
PPPPPPPPPPPPPPPPPPPP                              PPPPPPPPPPPPPPPPPPPP         
PPPPPPPPPPPPPPPPPPPP                               PPPPPPPPPPPPPPPPPPPP
PPPPPPPPPPPPPPPPPPPP                                PPPPPPPPPPPPPPPPPPPP
PPPPPPPPPPPPPPPPPPPP                                 PPPPPPPPPPPPPPPPPPPP
PPPPPPPPPPPPPPPPPPPP                                  PPPPPPPPPPPPPPPPPPPP
PPPPPPPPPPPPPPPPPPPP                                  PPPPPPPPPPPPPPPPPPPP
PPPPPPPPPPPPPPPPPPPP                                  PPPPPPPPPPPPPPPPPPPP
PPPPPPPPPPPPPPPPPPPP                                  PPPPPPPPPPPPPPPPPPPP
PPPPPPPPPPPPPPPPPPPP                                  PPPPPPPPPPPPPPPPPPPP
PPPPPPPPPPPPPPPPPPPP                                  PPPPPPPPPPPPPPPPPPPP
PPPPPPPPPPPPPPPPPPPP                                  PPPPPPPPPPPPPPPPPPPP
PPPPPPPPPPPPPPPPPPPP                                  PPPPPPPPPPPPPPPPPPPP
PPPPPPPPPPPPPPPPPPPP                                  PPPPPPPPPPPPPPPPPPPP
PPPPPPPPPPPPPPPPPPPP                                  PPPPPPPPPPPPPPPPPPPP
PPPPPPPPPPPPPPPPPPPP                                  PPPPPPPPPPPPPPPPPPPP
PPPPPPPPPPPPPPPPPPPP                                  PPPPPPPPPPPPPPPPPPPP
PPPPPPPPPPPPPPPPPPPP                                 PPPPPPPPPPPPPPPPPPPP
PPPPPPPPPPPPPPPPPPPP                                PPPPPPPPPPPPPPPPPPPP
PPPPPPPPPPPPPPPPPPPP                               PPPPPPPPPPPPPPPPPPPP
PPPPPPPPPPPPPPPPPPPP                              PPPPPPPPPPPPPPPPPPPP
PPPPPPPPPPPPPPPPPPPP                             PPPPPPPPPPPPPPPPPPPP
PPPPPPPPPPPPPPPPPPPP                            PPPPPPPPPPPPPPPPPPPP
PPPPPPPPPPPPPPPPPPPP                           PPPPPPPPPPPPPPPPPPPP
PPPPPPPPPPPPPPPPPPPP                          PPPPPPPPPPPPPPPPPPPP
PPPPPPPPPPPPPPPPPPPP                         PPPPPPPPPPPPPPPPPPPP
PPPPPPPPPPPPPPPPPPPP                        PPPPPPPPPPPPPPPPPPPP
PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP
PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP
PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP
PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP
PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP
PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP
PPPPPPPPPPPPPPPPPPPP
PPPPPPPPPPPPPPPPPPPP
PPPPPPPPPPPPPPPPPPPP
PPPPPPPPPPPPPPPPPPPP
PPPPPPPPPPPPPPPPPPPP
PPPPPPPPPPPPPPPPPPPP
PPPPPPPPPPPPPPPPPPPP
PPPPPPPPPPPPPPPPPPPP
PPPPPPPPPPPPPPPPPPPP
PPPPPPPPPPPPPPPPPPPP
PPPPPPPPPPPPPPPPPPPP
PPPPPPPPPPPPPPPPPPPP
PPPPPPPPPPPPPPPPPPPP
PPPPPPPPPPPPPPPPPPPP
PPPPPPPPPPPPPPPPPPPP
PPPPPPPPPPPPPPPPPPPP
PPPPPPPPPPPPPPPPPPPP
PPPPPPPPPPPPPPPPPPPP
PPPPPPPPPPPPPPPPPPPP
PPPPPPPPPPPPPPPPPPPP
PPPPPPPPPPPPPPPPPPPP
PPPPPPPPPPPPPPPPPPPP
PPPPPPPPPPPPPPPPPPPP
PPPPPPPPPPPPPPPPPPPP
PPPPPPPPPPPPPPPPPPPP
PPPPPPPPPPPPPPPPPPPP
















LLLLLLLLLLLLLLLLLLLL
LLLLLLLLLLLLLLLLLLLL
LLLLLLLLLLLLLLLLLLLL
LLLLLLLLLLLLLLLLLLLL
LLLLLLLLLLLLLLLLLLLL
LLLLLLLLLLLLLLLLLLLL
LLLLLLLLLLLLLLLLLLLL
LLLLLLLLLLLLLLLLLLLL
LLLLLLLLLLLLLLLLLLLL
LLLLLLLLLLLLLLLLLLLL
LLLLLLLLLLLLLLLLLLLL
LLLLLLLLLLLLLLLLLLLL
LLLLLLLLLLLLLLLLLLLL
LLLLLLLLLLLLLLLLLLLL
LLLLLLLLLLLLLLLLLLLL
LLLLLLLLLLLLLLLLLLLL
LLLLLLLLLLLLLLLLLLLL
LLLLLLLLLLLLLLLLLLLL
LLLLLLLLLLLLLLLLLLLL
LLLLLLLLLLLLLLLLLLLL
LLLLLLLLLLLLLLLLLLLL
LLLLLLLLLLLLLLLLLLLL
LLLLLLLLLLLLLLLLLLLL
LLLLLLLLLLLLLLLLLLLL
LLLLLLLLLLLLLLLLLLLL
LLLLLLLLLLLLLLLLLLLL
LLLLLLLLLLLLLLLLLLLL
LLLLLLLLLLLLLLLLLLLL
LLLLLLLLLLLLLLLLLLLL
LLLLLLLLLLLLLLLLLLLL
LLLLLLLLLLLLLLLLLLLL
LLLLLLLLLLLLLLLLLLLL
LLLLLLLLLLLLLLLLLLLL
LLLLLLLLLLLLLLLLLLLL
LLLLLLLLLLLLLLLLLLLL
LLLLLLLLLLLLLLLLLLLL
LLLLLLLLLLLLLLLLLLLL
LLLLLLLLLLLLLLLLLLLL
LLLLLLLLLLLLLLLLLLLL
LLLLLLLLLLLLLLLLLLLL
LLLLLLLLLLLLLLLLLLLL
LLLLLLLLLLLLLLLLLLLL
LLLLLLLLLLLLLLLLLLLL
LLLLLLLLLLLLLLLLLLLL
LLLLLLLLLLLLLLLLLLLL
LLLLLLLLLLLLLLLLLLLL
LLLLLLLLLLLLLLLLLLLL
LLLLLLLLLLLLLLLLLLLL
LLLLLLLLLLLLLLLLLLLL
LLLLLLLLLLLLLLLLLLLL
LLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL
LLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL
LLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL
LLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL
LLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL
LLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL
LLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL
LLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL
LLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL





















 YYYYYYYYYYYYYYYYYYYYYYYYYYYYYY                               YYYYYYYYYYYYYYYYYYYYYYYYYYYYYY
  YYYYYYYYYYYYYYYYYYYYYYYYYYYYYY                             YYYYYYYYYYYYYYYYYYYYYYYYYYYYYY
   YYYYYYYYYYYYYYYYYYYYYYYYYYYYYY                           YYYYYYYYYYYYYYYYYYYYYYYYYYYYYY
    YYYYYYYYYYYYYYYYYYYYYYYYYYYYYY                         YYYYYYYYYYYYYYYYYYYYYYYYYYYYYY
     YYYYYYYYYYYYYYYYYYYYYYYYYYYYYY                       YYYYYYYYYYYYYYYYYYYYYYYYYYYYYY
      YYYYYYYYYYYYYYYYYYYYYYYYYYYYYY                     YYYYYYYYYYYYYYYYYYYYYYYYYYYYYY
       YYYYYYYYYYYYYYYYYYYYYYYYYYYYYY                   YYYYYYYYYYYYYYYYYYYYYYYYYYYYYY
        YYYYYYYYYYYYYYYYYYYYYYYYYYYYYY                 YYYYYYYYYYYYYYYYYYYYYYYYYYYYYY
         YYYYYYYYYYYYYYYYYYYYYYYYYYYYYY               YYYYYYYYYYYYYYYYYYYYYYYYYYYYYY
          YYYYYYYYYYYYYYYYYYYYYYYYYYYYYY             YYYYYYYYYYYYYYYYYYYYYYYYYYYYYY
           YYYYYYYYYYYYYYYYYYYYYYYYYYYYYY           YYYYYYYYYYYYYYYYYYYYYYYYYYYYYY
            YYYYYYYYYYYYYYYYYYYYYYYYYYYYYY         YYYYYYYYYYYYYYYYYYYYYYYYYYYYYY
             YYYYYYYYYYYYYYYYYYYYYYYYYYYYYY       YYYYYYYYYYYYYYYYYYYYYYYYYYYYYY
              YYYYYYYYYYYYYYYYYYYYYYYYYYYYYY     YYYYYYYYYYYYYYYYYYYYYYYYYYYYYY
               YYYYYYYYYYYYYYYYYYYYYYYYYYYYYY   YYYYYYYYYYYYYYYYYYYYYYYYYYYYYY
                YYYYYYYYYYYYYYYYYYYYYYYYYYYYYY YYYYYYYYYYYYYYYYYYYYYYYYYYYYYY
                 YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY
                  YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY
                   YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY
                    YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY
                     YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY
                      YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY
                       YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY
                        YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY
                         YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY
                          YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY
                           YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY
                            YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY
                             YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY
                              YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY
                              YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY
                              YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY
                              YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY
                              YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY
                              YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY
                              YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY
                              YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY
                              YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY
                              YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY
                              YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY
                              YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY
                              YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY
                              YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY
                              YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY
                              YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY
                              YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY
                              YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY
                              YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY
                              YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY
                              YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY
                              YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY
                              YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY
                              YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY
                              YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY
                              YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY
                              YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY
                              YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY
                              YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY
                              YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY
                              YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY
                              YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY